/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

import DataModification.DataModificationForDatabase;
import DataModification.ReservationProcess;
import SystemObjects.ProgramUser;

/**
 *
 * @author juderafael
 */
public class AddReservations extends   JFrame {


    private ProgramUser refToCurrentProgramUser;
    /**
     * Creates new form AddReservations
     */
    public static void main(String[] args) {
        // AddReservations test = new AddReservations();
        // test.setVisible(true);
    }

    public AddReservations(ProgramUser currentUser) {
    
        refToCurrentProgramUser = currentUser;
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    
        initializeGUIComponents();

        setUpGUIComponents();

        setUpGroupLayout();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initializeGUIComponents() {

        Holder = new   JPanel();
        PanelHolder = new   JPanel();
        ReservationLabel = new   JLabel();
        AddReservationLabel = new   JPanel();
        StartingTimeLabel = new   JLabel();
        StartingTime = new   JTextField();
        FormatLabel = new   JLabel();
        EndingTime = new   JTextField();
        EndingTimeLabel = new   JLabel();
        PartySize = new   JTextField();
        PartySizeLabel = new   JLabel();
        AddCustomerPanel = new   JPanel();
        FirstNameLabel = new   JLabel();
        FirstName = new   JTextField();
        LastNameLabel = new   JLabel();
        LastName = new   JTextField();
        EmailLabel = new   JLabel();
        Email = new   JTextField();
        ContactNumber = new   JTextField();
        ContactNumberLavel = new   JLabel();
        AddReservation = new   JButton();
        // AddCustomerDetails = new   JButton();
    }

    private void setUpGUIComponents() {
    
        setDefaultCloseOperation(  JFrame.DISPOSE_ON_CLOSE);
        setPreferredSize(new   Dimension(700, 450));

        PanelHolder.setBackground(new   Color(255, 255, 255));

        ReservationLabel.setFont(new   Font("Poppins", 1, 18)); // NOI18N
        ReservationLabel.setForeground(new   Color(206, 66, 87));
        ReservationLabel.setText("ADD RESERVATIONS");

        AddReservationLabel.setBackground(new   Color(206, 66, 87));

        StartingTimeLabel.setFont(new   Font("Poppins", 0, 12)); // NOI18N
        StartingTimeLabel.setForeground(new   Color(255, 255, 255));
        StartingTimeLabel.setText("Starting Time ");

        StartingTime.addActionListener(new ActionListener() {
            public void actionPerformed( ActionEvent evt) {
                StartingTimeActionPerformed(evt);
            }
        });

        FormatLabel.setFont(new Font("Helvetica Neue", 0, 8)); // NOI18N
        FormatLabel.setForeground(new Color(255, 255, 255));
        FormatLabel.setText("Format: 2022 - month - day T 8:00:00PM");

        EndingTime.addActionListener(new  ActionListener() {
            public void actionPerformed( ActionEvent evt) {
                EndingTimeActionPerformed(evt);
            }
        });

        EndingTimeLabel.setFont(new   Font("Poppins", 0, 12)); // NOI18N
        EndingTimeLabel.setForeground(new   Color(255, 255, 255));
        EndingTimeLabel.setText("Ending Time ");

        PartySize.addActionListener(new  ActionListener() {
            public void actionPerformed( ActionEvent evt) {
                PartySizeActionPerformed(evt);
            }
        });

        PartySizeLabel.setFont(new   Font("Poppins", 0, 12)); // NOI18N
        PartySizeLabel.setForeground(new   Color(255, 255, 255));
        PartySizeLabel.setText("Party Size ");


        AddCustomerPanel.setBackground(new   Color(206, 66, 87));

        FirstNameLabel.setFont(new   Font("Poppins", 0, 12)); // NOI18N
        FirstNameLabel.setForeground(new   Color(255, 255, 255));
        FirstNameLabel.setText("First name");

        FirstName.addActionListener(new  ActionListener() {
            public void actionPerformed( ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });

        LastNameLabel.setFont(new   Font("Poppins", 0, 12)); // NOI18N
        LastNameLabel.setForeground(new   Color(255, 255, 255));
        LastNameLabel.setText("Last name");

        LastName.addActionListener(new  ActionListener() {
            public void actionPerformed( ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });

        EmailLabel.setFont(new   Font("Poppins", 0, 12)); // NOI18N
        EmailLabel.setForeground(new   Color(255, 255, 255));
        EmailLabel.setText("Email");

        ContactNumberLavel.setFont(new   Font("Poppins", 0, 12)); // NOI18N
        ContactNumberLavel.setForeground(new   Color(255, 255, 255));
        ContactNumberLavel.setText("Contact number");

        
        AddReservation.setForeground(new   Color(206, 66, 87));
        AddReservation.setText("Add Reservation");
        AddReservation.setPreferredSize(new   Dimension(127, 30));
        AddReservation.addActionListener(addReservationAction);

        // AddCustomerDetails.setForeground(new   Color(206, 66, 87));
        // AddCustomerDetails.setText("Add Customer Details");
        // AddCustomerDetails.setPreferredSize(new   Dimension(158, 30));
        // AddCustomerDetails.addActionListener(new  ActionListener() {
        //     public void actionPerformed( ActionEvent evt) {
        //         AddCustomerDetailsActionPerformed(evt);
        //     }
        // });

    }

    private void setUpGroupLayout() {

        GroupLayout AddReservationLabelLayout = new   GroupLayout(AddReservationLabel);
        AddReservationLabel.setLayout(AddReservationLabelLayout);
        AddReservationLabelLayout.setHorizontalGroup(
            AddReservationLabelLayout.createParallelGroup(  GroupLayout.Alignment.LEADING)
            .addGroup(  GroupLayout.Alignment.TRAILING, AddReservationLabelLayout.createSequentialGroup()
                .addGroup(AddReservationLabelLayout.createParallelGroup(  GroupLayout.Alignment.TRAILING)
                    .addGroup(  GroupLayout.Alignment.LEADING, AddReservationLabelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(FormatLabel)
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addGroup(  GroupLayout.Alignment.LEADING, AddReservationLabelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(AddReservationLabelLayout.createParallelGroup(  GroupLayout.Alignment.LEADING)
                            .addComponent(EndingTime,   GroupLayout.Alignment.TRAILING)
                            .addComponent(StartingTime)
                            .addGroup(AddReservationLabelLayout.createSequentialGroup()
                                .addGroup(AddReservationLabelLayout.createParallelGroup(  GroupLayout.Alignment.LEADING)
                                    .addComponent(PartySizeLabel)
                                    .addComponent(EndingTimeLabel)
                                    .addComponent(StartingTimeLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(PartySize))))
                .addGap(28, 28, 28))
        );
        AddReservationLabelLayout.setVerticalGroup(
            AddReservationLabelLayout.createParallelGroup(  GroupLayout.Alignment.LEADING)
            .addGroup(AddReservationLabelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(StartingTimeLabel)
                .addPreferredGap(  LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartingTime,   GroupLayout.PREFERRED_SIZE,   GroupLayout.DEFAULT_SIZE,   GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(  LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FormatLabel)
                .addGap(12, 12, 12)
                .addComponent(EndingTimeLabel)
                .addGap(8, 8, 8)
                .addComponent(EndingTime,   GroupLayout.PREFERRED_SIZE,   GroupLayout.DEFAULT_SIZE,   GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PartySizeLabel)
                .addPreferredGap(  LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PartySize,   GroupLayout.PREFERRED_SIZE,   GroupLayout.DEFAULT_SIZE,   GroupLayout.PREFERRED_SIZE)
                .addContainerGap(  GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout AddCustomerPanelLayout = new   GroupLayout(AddCustomerPanel);
        AddCustomerPanel.setLayout(AddCustomerPanelLayout);
        AddCustomerPanelLayout.setHorizontalGroup(
            AddCustomerPanelLayout.createParallelGroup(  GroupLayout.Alignment.LEADING)
            .addGroup(AddCustomerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(AddCustomerPanelLayout.createParallelGroup(  GroupLayout.Alignment.LEADING, false)
                    .addComponent(LastNameLabel)
                    .addComponent(FirstNameLabel)
                    .addComponent(EmailLabel)
                    .addComponent(ContactNumberLavel)
                    .addComponent(FirstName,   GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(LastName)
                    .addComponent(Email)
                    .addComponent(ContactNumber))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        AddCustomerPanelLayout.setVerticalGroup(
            AddCustomerPanelLayout.createParallelGroup(  GroupLayout.Alignment.LEADING)
            .addGroup(AddCustomerPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(FirstNameLabel)
                .addPreferredGap(  LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstName,   GroupLayout.PREFERRED_SIZE,   GroupLayout.DEFAULT_SIZE,   GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LastNameLabel)
                .addPreferredGap(  LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastName,   GroupLayout.PREFERRED_SIZE,   GroupLayout.DEFAULT_SIZE,   GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmailLabel)
                .addPreferredGap(  LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email,   GroupLayout.PREFERRED_SIZE,   GroupLayout.DEFAULT_SIZE,   GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ContactNumberLavel)
                .addPreferredGap(  LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContactNumber,   GroupLayout.PREFERRED_SIZE,   GroupLayout.DEFAULT_SIZE,   GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );


        GroupLayout PanelHolderLayout = new   GroupLayout(PanelHolder);
        PanelHolder.setLayout(PanelHolderLayout);
        PanelHolderLayout.setHorizontalGroup(
            PanelHolderLayout.createParallelGroup(  GroupLayout.Alignment.LEADING)
            .addGroup(PanelHolderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelHolderLayout.createParallelGroup(  GroupLayout.Alignment.LEADING)
                    .addGroup(PanelHolderLayout.createSequentialGroup()
                        .addComponent(ReservationLabel)
                        .addContainerGap(  GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelHolderLayout.createSequentialGroup()
                        .addComponent(AddReservationLabel,   GroupLayout.DEFAULT_SIZE,   GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(  LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddCustomerPanel,   GroupLayout.PREFERRED_SIZE,   GroupLayout.DEFAULT_SIZE,   GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(PanelHolderLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(AddReservation,   GroupLayout.PREFERRED_SIZE,   GroupLayout.DEFAULT_SIZE,   GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(  LayoutStyle.ComponentPlacement.RELATED,   GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                // .addComponent(AddCustomerDetails,   GroupLayout.PREFERRED_SIZE, 185,   GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        PanelHolderLayout.setVerticalGroup(
            PanelHolderLayout.createParallelGroup(  GroupLayout.Alignment.LEADING)
            .addGroup(  GroupLayout.Alignment.TRAILING, PanelHolderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ReservationLabel)
                .addGap(18, 18, 18)
                .addGroup(PanelHolderLayout.createParallelGroup(  GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddCustomerPanel,   GroupLayout.DEFAULT_SIZE,   GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddReservationLabel,   GroupLayout.DEFAULT_SIZE,   GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(  LayoutStyle.ComponentPlacement.RELATED,   GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelHolderLayout.createParallelGroup(  GroupLayout.Alignment.BASELINE)
                    .addComponent(AddReservation,   GroupLayout.PREFERRED_SIZE,   GroupLayout.DEFAULT_SIZE,   GroupLayout.PREFERRED_SIZE)
                                        // .addComponent(AddCustomerDetails, GroupLayout.PREFERRED_SIZE,
                                        //         GroupLayout.DEFAULT_SIZE,
                                        //         GroupLayout.PREFERRED_SIZE)
                    )
                .addContainerGap())
        );


        GroupLayout HolderLayout = new   GroupLayout(Holder);
        Holder.setLayout(HolderLayout);
        HolderLayout.setHorizontalGroup(
            HolderLayout.createParallelGroup(  GroupLayout.Alignment.LEADING)
            .addComponent(PanelHolder,   GroupLayout.DEFAULT_SIZE,   GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HolderLayout.setVerticalGroup(
            HolderLayout.createParallelGroup(  GroupLayout.Alignment.LEADING)
            .addComponent(PanelHolder,   GroupLayout.DEFAULT_SIZE,   GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        GroupLayout layout = new   GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(  GroupLayout.Alignment.LEADING)
            .addComponent(Holder,   GroupLayout.DEFAULT_SIZE,   GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(  GroupLayout.Alignment.LEADING)
            .addComponent(Holder,   GroupLayout.DEFAULT_SIZE,   GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

    }



    // I don't know what is the purpose of adding an action listener to a jtextfield would do
    //TODO Disregard the Textfields function it is used to see the needed fields and buttons
    private void EndingTimeActionPerformed( ActionEvent evt) {//GEN-FIRST:event_EndingTimeActionPerformed
        // TODO EndingTime
    }//GEN-LAST:event_EndingTimeActionPerformed

    private void StartingTimeActionPerformed( ActionEvent evt) {//GEN-FIRST:event_StartingTimeActionPerformed
        // TODO StartingTime
    }//GEN-LAST:event_StartingTimeActionPerformed

    private void AddReservationActionPerformed( ActionEvent evt) {//GEN-FIRST:event_AddReservationActionPerformed
        // TODO AddReservationButton
    }//GEN-LAST:event_AddReservationActionPerformed

    private void AddCustomerDetailsActionPerformed( ActionEvent evt) {//GEN-FIRST:event_AddCustomerDetailsActionPerformed
        // TODO AddCustomerDetailsButton
    }//GEN-LAST:event_AddCustomerDetailsActionPerformed

    private void PartySizeActionPerformed( ActionEvent evt) {//GEN-FIRST:event_PartySizeActionPerformed
        // TODO PartySize
    }//GEN-LAST:event_PartySizeActionPerformed

    private void FirstNameActionPerformed( ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO FirstName
    }//GEN-LAST:event_FirstNameActionPerformed

    private void LastNameActionPerformed( ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO LastName
    }//GEN-LAST:event_LastNameActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    
    // jpanel
    private   JPanel AddReservationLabel;
    private   JPanel Holder;
    private   JPanel PanelHolder;
    private   JPanel AddCustomerPanel;
    
    
    // jtextfield
    private JTextField ContactNumber;
    private   JTextField Email;
    private   JTextField FirstName;
    private JTextField LastName;
    
    private   JTextField PartySize;
    private   JTextField StartingTime;
    private JTextField EndingTime;

    // jlabel 
    private JLabel ContactNumberLavel;
    private JLabel StartingTimeLabel;
    private JLabel PartySizeLabel;
    private JLabel ReservationLabel;
    private JLabel LastNameLabel;
    private JLabel FirstNameLabel;
    private JLabel FormatLabel;
    private JLabel EndingTimeLabel;
    private JLabel EmailLabel;
    
    // jbutton
    // private JButton AddCustomerDetails;
    private JButton AddReservation;

    private ActionListener addReservationAction = (event) -> {
        
        int contactNumberConverted = -1;
        int partySizeNum = -1;
        int roomid = -1;
        try {
            contactNumberConverted = Integer.parseInt(ContactNumber.getText());
            
            partySizeNum = Integer.parseInt(PartySize.getText());
        
            roomid = Integer.parseInt(
                JOptionPane.showInputDialog(
                    null,
                    "NOTE : ROOM MUST BE AVAILABLE\nEnter the ID of the Room for the Reservation : ",
                    "Input Room Id For Reservation",
                     JOptionPane.QUESTION_MESSAGE
                )
            );
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    null,
                    "please input numbers only.",
                    "Reservation Entry input warning",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DataModificationForDatabase.createReservationAndCustomerEntry(
            refToCurrentProgramUser,

            // data for customer 
            FirstName.getText(),
            LastName.getText(),
            Email.getText(),
            contactNumberConverted,

            // data for reservation
            StartingTime.getText(),
            EndingTime.getText(),
            partySizeNum,
            roomid
        );



        
    };

    // End of variables declaration//GEN-END:variables
}
